### ISSUE TITLE
Support for multiple uploads in same project

### ISSUE THREAD

**Issue by maxnowack** [yongkangchen/remote-sync#105]
Is there a way to upload files to different servers at the same time?
Like putting an array of configs in the `.remote-sync.json`

**Comment by daithi-coombes** [comment]
+1 for this as a feature request.

**Comment by yongkangchen** [comment]
supported in 9cfa73d9f3859ac1f648082cd122bd6deebf9aed, thanks

**Comment by maxnowack** [comment]
Thank you! 
how can I configure it? please update the readme :)

**Comment by yongkangchen** [comment]
@maxnowack updated the readme, see `Upload mirrors example`

**Comment by yongkangchen** [comment]
@maxnowack also please make sure the latest version of remote-sync@v3.1.0
