### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by brunopincaro** [yongkangchen/remote-sync#108]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/exports/atom.js:43:9)
Object.<anonymous> (/Users/bruno/.atom/packages/remote-sync/lib/RemoteSync.coffee:4:1)
```

**Comment by yongkangchen** [comment]
Will be fixed in #135, so I will close this.
