### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by wardtm11** [yongkangchen/remote-sync#112]
Requiring `View` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{View} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\<user>\AppData\Local\atom\app-0.189.0\resources\app\exports\atom.js:61:9)
Object.<anonymous> (C:\Users\<user>\.atom\packages\remote-sync\lib\view\StatusView.coffee:1:1)
```

**Comment by yongkangchen** [comment]
duplicate with #108
