### ISSUE TITLE
Problems with Project folders

### ISSUE THREAD

**Issue by brianmhunt** [yongkangchen/remote-sync#114]
If one has projects A (with a `.remote-sync.json`) and B (without), if one opens with "Add Project Folder" A then B then when one saves something in B it is synced.

If one opens project B then A then this does not occur.

The correct behaviour would be to ensure that the file being saved is in the current project directory i.e. the `.remote-sync.json` is in the current or parent directory of the file being saved.

:beers:

**Comment by yongkangchen** [comment]
Support with multiple projects will be implement in #135

**Comment by brianmhunt** [comment]
Awesome; ty.
