### ISSUE TITLE
Uploading to a file system?

### ISSUE THREAD

**Issue by kupoback** [yongkangchen/remote-sync#116]
I am working at a web firm who also hosts websites on our own personal server.

We have network connection shortcuts allowing us to automatically connect to them via windows explorer. Our file or connection structure is like so:

    \\Ics-dev-01\www\domain.dev.com

I am wondering if there is a way to connect to that file system through the SFTP.

Granted I can work from the server with no issues, however we use bitbucket for repositories so I must work off the files on my local machine and upload to our dev server.

**Comment by yongkangchen** [comment]
duplicate with #179
