### ISSUE TITLE
IDEA : laravel specific...kinda.. "Forwarders"

### ISSUE THREAD

**Issue by Goddard** [yongkangchen/remote-sync#117]
This might be a little to specific to incorporate and this isn't exactly an issue, but I wanted to make a suggestion.

Would it be possible to put folder specific forwarders.  For example in most shared hosting environments that use cpanel the web root is "public_html" and in laravel the web root is "public".

It would be super awesome if I could have a directory forwarder in this specific situation to automatically save and watch the directory for changes to upload files to "public_html" instead of "public"

forwarders: {
   "public": "public_html"
}

I don't know...thanks for the awesome add-on.

**Comment by CupCoffee** [comment]
Excuse me for commenting on this without contributing to this issue regarding this package but i solved  this by making a symlink between the folders.

**Comment by Goddard** [comment]
I haven't looked very deeply into this, but I heard this requires changing your server configuration - http://stackoverflow.com/questions/26558341/how-to-make-a-public-html-in-whm-cpanel-symlink

**Comment by CupCoffee** [comment]
Sorry for my late response, you might have already fixed this but just incase you didn't.
you can create symlinks using the cli. It might depend on your OS but here's a reference:
http://stackoverflow.com/questions/1951742/how-to-symlink-a-file-in-linux
