### ISSUE TITLE
Suggestion: Add package option to set config JSON filename

### ISSUE THREAD

**Issue by Alhadis** [yongkangchen/remote-sync#118]
I work with a team of Sublime users, so all our repos have their `.gitignore` files set to skip `sftp-config.json` in project directories. It'd be nice to give Atom users a choice of specifying what filenames to use to hold remote-sync's S/FTP details, to avoid the hassle of another commit for every project.

The option could possibly take the form of an ordered list of filenames, with remote-sync searching for each of them in order until it finds a file in a project directory that matches. E.g., something like this:
````
.remote-sync.json
remote-sync.json
sftp-config.json
deployment-details.json
````

**Comment by yongkangchen** [comment]
supported in 9cfa73d9f3859ac1f648082cd122bd6deebf9aed
