### ISSUE TITLE
Option to download on open

### ISSUE THREAD

**Issue by egyptianbman** [yongkangchen/remote-sync#129]
I usually rsync a whole project locally so an option to sync down a file when I open it locally would be awesome, thanks!

**Comment by mbuquet** [comment]
I would also like to see this feature. Right now every time I open a file for editing I have to remember to download it from the server to make sure I have the latest version.

**Comment by marekmaurizio** [comment]
+

**Comment by yongkangchen** [comment]
Duplicate with #85
