### ISSUE TITLE
Confusion when multiple project folders

### ISSUE THREAD

**Issue by kdemarest** [yongkangchen/remote-sync#131]
My usage pattern is to have many project folders open at once in Atom (that is, I use File/Add Project Folder)

When I attempt to "remote sync reload config" it seems to get stuck on one of the other folders.

What I need is for remote sync to look at the .remote-sync.json file that is in the same directory as the file I am editing, and use that during a save.  If that .json file is not found, it should look up directories until it finds one.

**Comment by yongkangchen** [comment]
Support with multiple projects will be implement in #135
