### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by mikecg** [yongkangchen/remote-sync#132]
I cannot download anything from my FTP server. After configuring everything in .remote-sync.json, I get the following error when trying to download all files:

Error: getaddrinfo ENOTFOUND

As a result, I cannot use this package. I am on windows 7 x64.

**Comment by yongkangchen** [comment]
Please check host name in `.remote-sync.json`

**Comment by Bertutchio** [comment]
For those who land here. it need to be the ip addr.
