### ISSUE TITLE
Cannot Create Folder on Download All Command

### ISSUE THREAD

**Issue by danieldogeanu** [yongkangchen/remote-sync#134]
When I try to run the `Download All` command it starts downloading all the files, until it hits a folder and then gives me this error:

```
[1:41:59 AM] Download: //wp-admin/about.php to \\wp-admin\about.php\ ...
Error: UNKNOWN: unknown error, mkdir '\\wp-admin\about.php\'
```

Even if I create the folder manually, I get the same error. It seems that it can't create a folder for whatever reason. Is this feature supported on Windows?

**Comment by yongkangchen** [comment]
I guess `wp-admin` exist in remote shared folder?

**Comment by danieldogeanu** [comment]
Hm... What do you mean by shared? Folder permissions? It's a WordPress site with dedicated FTP account.

**Comment by yongkangchen** [comment]
I guess you use windows? And `wp-admin` is a windows shared folder?

**Comment by danieldogeanu** [comment]
I use Windows, but the folder is on a Linux server.

**Comment by yongkangchen** [comment]
Is this issue still? May be you can show me the path of "target" in .remote-sync.json and the path of your project?

**Comment by danieldogeanu** [comment]
I haven't tried it in a while, I'll let you know tomorrow when I'll have the time. But as far as I can tell, it doesn't allow me to download the full installation of WordPress, but it's ok for downloading and editing a single theme.

**Comment by elistone** [comment]
@danieldogeanu is this still an issue?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
