### ISSUE TITLE
Could not chdir to home directory

### ISSUE THREAD

**Issue by jbh** [yongkangchen/remote-sync#138]
I am continuously getting this error when trying to download a directory. Downloading/uploading individual files works fine, but not a directory. I'm on Ubuntu 14.04 and the latest version of atom. Here is my config (sans the sensitive parts):

```json
// In /home/user/Sites/ProjectIAmWorkingOn
{
  "transport": "scp",
  "hostname": "xxx.xxx.xxx.xx",
  "port": "22",
  "username": "username",
  "password": "password",
  "target": "/correct/path",
  "ignore": [
    ".git/**"
  ],
  "uploadOnSave": true
}
```

Pretty simple and straight forward. I've checked permissions as well; they all seem up to par. The error message doesn't even make sense, because it's talking about a directory that isn't even related to the path I'm working in. It's talking about a path in another sub-directory of my local.

`/home/user/Sites/ProjectIAmWorkingOn` is what I need to be syncing and where all the settings are. The error reads `Could not chdir to home directory /home/USER: A file or directory in the path name does not exist. to /home/user/Projects/RandomProject`. How could this be?

**Comment by yongkangchen** [comment]
I notice that `USER ` in `Could not chdir to home directory /home/USER`, it seems that you should use lower case?

**Comment by jbh** [comment]
I was using `/home/USER` as an example user. Our usernames are all caps due to the system we are working on. It is not the case sensitivity that is the problem, and it is still occurring unfortunately. At the moment I'm having to keep using Sublime because Atom doesn't have a workable plugin.
