### ISSUE TITLE
Sync silently failing

### ISSUE THREAD

**Issue by borgand** [yongkangchen/remote-sync#141]
I have
* Atom: 0.201.0
* remote-sync: 3.0.1

I installed the script earlier today, but didn't check it out. Now both Atom and the script reported updates, which I installed and restarted (many times to be on the safe side).

Now I configured a project's remote location, but neither uploading nor downloading works. In the status window, uploading reports only once that it is uploading the file, after that it seems not to work (restarting Atom again gives one upload). Downloading resports every time the same lines.

I tried to deliberately misconfigure and with invalid hostname or username I get the expected error message, but not with nonexistant path:

```
[21:55.37] Connecting: laas@hostname:22
[21:55.37] Upload: /Users/laas/project/myscript.sh to /nonexistant/myscript.sh ...
[21:55.48] Connecting: laas@hostname:22
[21:55.49] Download: /nonexistant/myscript.sh to /Users/laas/project/myscript.sh ...
```

**Comment by yongkangchen** [comment]
Sorry that I can help you in this issue. I suggest you add log in source code by open atom->preferences->package->remote-sync->view code, and see where it stops
