### ISSUE TITLE
Uploadonsave:false - not honoring the rule

### ISSUE THREAD

**Issue by djdesign** [yongkangchen/remote-sync#146]
I am running into the issue when I save my work, remote-sync still pushes my changes even if its specifically is ,disabled/ set to false, in the settings area and in the individual .remote-sync.json file. 

Atom v0.201.0 (0.201.0), Remote-Sync v3.1.1
Steps taken to attempt to resolve with no success. Try a fresh install and the plugin, set settings to no checked for upload on save and reset atom. 

Please advise.

**Comment by yongkangchen** [comment]
Please check `"uploadOnSave": false` in `.remote-sync.json`, or you can update the package to the latest and try again.
