### ISSUE TITLE
IDEA: if i save scss file also sync generated css file

### ISSUE THREAD

**Issue by 0x746f6d** [yongkangchen/remote-sync#149]
i use the sass-autocompile package.

if i save the scss file it automatically updates the css file. but to sync the css file i always have to switch to its tab and do a save there.

it would be awesome if remote-sync could notice the changed css file and sync it automatically too.

**Comment by stillworks** [comment]
We definitely need something like this.

**Comment by siilak** [comment]
True!

**Comment by timkirtley** [comment]
This would really be a helpful feature.  I found a fork (https://github.com/theproducer/remote-sync) that supposedly added the functionality but it is now depreciated so no use

**Comment by theproducer** [comment]
https://github.com/theproducer/remote-sync

I've just updated for the latest version of Remote Sync.  I've been using it daily for a few weeks now, fixing bugs as I come across them.

**Comment by timkirtley** [comment]
@theproducer - hey, thanks for the update - it works great, the only problem being I havent been able to add multiple files to be watched.  I've tried:

    "watch": [
        "/wp-content/themes/nfh/media/css/screen.css","/wp-content/themes/nfh/media/js/scripts.min.js"
    ]

But I get an error when I try to save the `.remote-sync.json` file: "Uncaught Error: Unable to watch path"

Am I incorrectly adding the multiple file paths?

**Comment by theproducer** [comment]
It will do that if it can't find the path/file.  Soon i'll add in some more user friendly error messages.

Does scripts.min.js exist yet?  Just make sure the path is correct too.

**Comment by timkirtley** [comment]
Yeah the file does exist, if I just put either of those file paths in on their own they work, its just if I put the two of them as above then I get the error.

**Comment by theproducer** [comment]
I see.  I'll reproduce this and try to get a fix out..maybe today even.

**Comment by oomathias** [comment]
:+1:

What's the status on this? Have you made a PR?

**Comment by yongkangchen** [comment]
Upload mirrors example in README will help you?

**Comment by timkirtley** [comment]
Isnt 'Upload mirrors' for uploading a file to two different remote places at the same time?

The functionality in the @theproducer fork means you can watch a separate local file for changes and have that automatically uploaded.  Using a css preprocessor for example makes this feature really important.  Unless I'm misunderstanding it, you can't do that just using the 'Upload mirror' setting?
