### ISSUE TITLE
Wrong upload target (Uploads on same local path)

### ISSUE THREAD

**Issue by Mehdi-Hp** [yongkangchen/remote-sync#153]
The `target` in `.remote-sync.json` is set to `/www`; But my files are uploading to the same target as my local path.  

![anim](https://cloud.githubusercontent.com/assets/8641684/8019011/8481b3be-0c4e-11e5-9839-c0c83b564ebb.gif)

**Comment by primiano** [comment]
Same thing here after the last update (3.1.2)

**Comment by mmolnar** [comment]
This happens if you have a symlink in your project path.
See issue #181 .
