### ISSUE TITLE
Add watch functionallity

### ISSUE THREAD

**Issue by visualcookie** [yongkangchen/remote-sync#154]
Hi,

I would like to request a watch functionallity, which allows me to watch a folder for upcoming changes (e.g. compiler changes), so it uploads, when a file is written in there.

Hope this will work and it can be implemented in the nearest future. :+1:

**Comment by theproducer** [comment]
A few months ago I created a fork of this project to experimentally add this in:
https://github.com/theproducer/remote-sync

Its not fully tested, but try it out!

**Comment by yongkangchen** [comment]
Duplicate with #65. And @theproducer it would be nice if you fully tested and send a pull request to me :)

**Comment by theproducer** [comment]
Lol, sure thing!

**Comment by Safe-Mode** [comment]
Would be so nice to see this feature in the stable version of plugin!

**Comment by Safe-Mode** [comment]
> A few months ago I created a fork of this project to experimentally add this in:
> https://github.com/theproducer/remote-sync
> 
> Its not fully tested, but try it out!

So, How could we install exactly that version, with watch folder feature?
