### ISSUE TITLE
Project I use won't upload or give errors

### ISSUE THREAD

**Issue by kupoback** [yongkangchen/remote-sync#157]
I am using this to sync with a site with port 2222, however when I save and upload, I get nothing.

No prompt, no visual of the eye and the config remote, no popup at the bottom indicating that it's connecting...uploading.

However on other projects I'll get the popup, despite the visual eye and config remote on the bottom right of the taskbar doesn't show.

Any ideas? Any information you need?

**Comment by kupoback** [comment]
UPDATE: 
I got the program to finally work, however now I run into the issue `Error: Unable to exec`

Not sure what the issue would be as I'm able to use the same credentials with FileZilla

**Comment by yongkangchen** [comment]
Duplicate with #137
