### ISSUE TITLE
No response or feedback

### ISSUE THREAD

**Issue by aaronmoodie** [yongkangchen/remote-sync#169]
I've just  re-installed the package, and re-setup the remote-sync file, but nothing seems to be uploading and I am getting no response or errors when saving. I've got 'Log to console' checked, but not seeing anything there either. 

I'm using v1.0.0 of Atom.

**Comment by marcoslhc** [comment]
Same here. Could this be related to https://github.com/yongkangchen/remote-sync/issues/147?

**Comment by aaronmoodie** [comment]
ok, sorted this out. when I last used the package, `"uploadOnSave": true` wasn't required. Files are uploading now.

**Comment by n0mad01** [comment]
I had this issue after installing remote-sync and restarting Atom then adding the .remote-sync.json file and trying to upload/sync.

After another restart of Atom everything is fine.
