### ISSUE TITLE
error when saving .remote-sync.json

### ISSUE THREAD

**Issue by n9iels** [yongkangchen/remote-sync#171]
When I save the remote path of the .remote-sync.json file, to edit the remote path for example, I receive the following error
```
C:\Users\Niels van der Veer\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:762
```

I'm using atom 1.0

**Comment by Sigmanor** [comment]
I got this error when i used remote-sync for upload file to ftp/etc, just reload atom.
