### ISSUE TITLE
uploadOnSave saves to local path instead of remote target

### ISSUE THREAD

**Issue by mmolnar** [yongkangchen/remote-sync#181]
When saving the file with uploadOnSave turned on the package just copies the file into the same location, this is the log output:
```
[1:37:39 PM] Upload: /path/to/recently/saved/file to /path/to/recently/saved/file ... Complete (256ms)
```

Using the options:
```
  "uploadOnSave": true,
  "transport": "scp",
  "useAgent": true,
```

**Comment by akamizi** [comment]
confirm, my options:
{
  "uploadOnSave": true,
  "hostname": "xxxx.xx",
  "port": "2222",
  "target": "/var/www/xxx/xxx/xxx/",
  "ignore": [
    ".git/**"
  ],
  "username": "xxxxx",
  "keyfile": "/home/xxxx/.ssh/id_rsa",
  "transport": "scp"
}

**Comment by akamizi** [comment]
sorry wrong report: save on the remote server, but recreates the same local path, and don't use the path specified in the configuration. Same issue with rightclick-menu in text area. No issue from rightclick-menu in files tree.

**Comment by mmolnar** [comment]
Actually the problem was that it uploaded to the target host with full local path instead of target path.

And it only happened if the project path contained a symlink.
