### ISSUE TITLE
Download error file with cyrillic symbols

### ISSUE THREAD

**Issue by fzhukov** [yongkangchen/remote-sync#183]
Then i try download file with cyrillic symbols in the name, i getting this error
Error: /folder/ÃÂÃÂµÃÂ·ÃÂÃÂ¼ÃÂÃÂ½ÃÂ½ÃÂÃÂ¹ ÃÂ´ÃÂ¾ÃÂºÃÂÃÂ¼ÃÂµÃÂ½ÃÂ~

But if file already there with same name and i trying download it, it's ok, download successful and cyrillic symbols in log looks normal.

Linux
Atom 1.0.0
remote-sync 3.1.2

**Comment by yongkangchen** [comment]
should fixed by #186
