### ISSUE TITLE
Sync local folder

### ISSUE THREAD

**Issue by dmaglio** [yongkangchen/remote-sync#187]
Is it possible to sync a local folder with another local folder? I have my development folder into my home and testing folder in /var/www/html and i want to sync directly from Atom

**Comment by yongkangchen** [comment]
You can add a local transport for remote-sync and pull a request. See https://github.com/yongkangchen/remote-sync/tree/master/lib/transports

**Comment by yongkangchen** [comment]
Duplicate with #179
