### ISSUE TITLE
Error: Unable to exec

### ISSUE THREAD

**Issue by Alexadar** [yongkangchen/remote-sync#188]
Hi
Im trying to Diff local folder with SFTP site.

Log:
[3:19:10 PM] Downloading all files: %mypath%
[3:19:10 PM] Connecting: account@host:21
Error: Unable to exec

Possible issues: website use self-signed certificate and user\pass auth

Is it a bug or i should somehow configure package to use self-signed certs?

**Comment by Alexadar** [comment]
Update:
I printed command after error message, so i got: Error: 

"Unable to exec find "my remote path to directory" -type f"

My ftp account have access to that directory

**Comment by yongkangchen** [comment]
could you please put the full error message here?

**Comment by yongkangchen** [comment]
Duplicate with #137?
