### ISSUE TITLE
Remote sync with support for recursive subfolders

### ISSUE THREAD

**Issue by shawe** [yongkangchen/remote-sync#192]
I'm developing some plugins for FacturaScripts available here on github, and I've found a "big" problem, I explain my case for a better understood, because I think that is a better way for work in big projects.

I use this structure of folders for development "/home/shawe/Projects" that contains "/home/shawe/Projects/FS_2015", "/home/shawe/Projects/plugin_1", "/home/shawe/Projects/plugin_2", ...

And for testing, the folder FS_2015 is synced to "/var/html" and the plugins are synced to "/var/html/plugins/plugin_X", with this I can work without lose nothing by error testing the changes, like delete plugin.

The problem is that remote-sync don't support "remote sync project upload/download/diff files/folders", doing a remote sync of every folder inside this level. Similar to do a manual "remote sync upload/download/diff file/folder" on every folder. The remote sync also is only working well if I "Open in new window" for every subfolder in my project folder, causing a big lose of time.

You can see on NetBeans that every subproject loaded on your workspace (aka Project Folder) have this type of sync for every subproject, and with your package using localhost as hostname we can have the same feature that is very usefull, but require this style of recursive sync by folder with different configuration.

For me, I think that only is needed add some extra commands for get this feature, that maybe can be do it with only adding some little changes.

**Comment by yongkangchen** [comment]
Duplicate with #160
