### ISSUE TITLE
Can I use it with Linux and Windows?

### ISSUE THREAD

**Issue by l222p** [yongkangchen/remote-sync#200]
I am working with a server in Linux, and I program in Windows, can i use it with Windows and Linux?
I have a problem with that

**Comment by lukehsiao** [comment]
Is there any followup on this? Were you able to get it to work? If not, what did you decide to use?

I'm currently running a linux VM that I would like to connect with from my Windows host. However, I get errors like this:
```
[4:11:57 PM] Connecting: cs@192.168.56.11:22
[4:11:59 PM] Download: find: `~/cs/router/': No such file or directory to C:\find: `~\cs\router\': No such file or directory ...
```
which makes me feel like the '/' vs '\' is causing an issue. If Windows to Linux does work, could somebody explain what you have to do to get it connected?

**Comment by l222p** [comment]
Yes, it works. I had wrong the configuration.

i don't know if a git shell is necesary, because I conect to the VM Linux by ssh, using the git shell.

**Comment by lukehsiao** [comment]
I'm still having an issue with it. I have Git shell installed, but I
thought that the connection was made by Atom using the details specified in
the configuration file. Can you explain what you had to do to get this to
work?

**Comment by l222p** [comment]
I have my VM Linux like a server (obviusly in network).

My config
![sin titulo](https://cloud.githubusercontent.com/assets/11236950/10525310/38504bf4-7341-11e5-8214-0f783310fd7d.png)

I use ssh to conect it (ssh)
HostName: IP Server
Port 22 (ssh)
Target Directory: folder of my app
Username: User of my VM
password: Pass of User

and click at checkbox.
This is it

PD: Sorry for my bad English

**Comment by lukehsiao** [comment]
Great. This worked for me as well. @yongkangchen You can probably go ahead and close this issue.

**Comment by yongkangchen** [comment]
@lukehsiao  ok, and thanks for consulting this issue.
