### ISSUE TITLE
monitor files

### ISSUE THREAD

**Issue by robsonsobral** [yongkangchen/remote-sync#209]
Hi!

Please, is there a way to monitor files for changes and upload them? Let's say, I want to monitor all CSS and JS files or a specific folder to be uploaded on the fly; is there a configuration for it?

Thank you for the addon and for your attention.

**Comment by robsonsobral** [comment]
I found somebody who [implemented it](https://github.com/theproducer/remote-sync).

Is there a chance of accepted a pull request from @theproducer?

**Comment by yongkangchen** [comment]
What do you mean `changes`? Changes not modified by atom editor?

**Comment by robsonsobral** [comment]
Yes. Some files can be edited by preprocessors, for example.

**Comment by yongkangchen** [comment]
so it duplicate with #65, not in support plan yet. But a pull request is welcome. Thanks for this issue
