### ISSUE TITLE
[DOC] remote sync config reload

### ISSUE THREAD

**Issue by pniederlag** [yongkangchen/remote-sync#216]
error: no matches

atom running on debian linux host

**Comment by yongkangchen** [comment]
can you provide the full error which include the traceback?

**Comment by chris-aeviator** [comment]
i think what @pniederlag means is that there is no remote sync config reload function when cmd + p'ing

**Comment by JustinRvt** [comment]
Same here :v

**Comment by toledosteve** [comment]
Same here.  On Macbook Pro and there is no matching command for `remote sync config reload`

**Comment by capay** [comment]
Same here. I use Debian 8 and the window opened by `ctrl + shift + p` does not offer me anything when looking for `remote sync config reload`.

**Comment by dmquadrat** [comment]
Does somebody know another way to do reload it?

**Comment by juanmirocks** [comment]
Same here. OS X 10.11.4

**Comment by juanmirocks** [comment]
Indeed, it just seems to be a documentation issue. Nonetheless remote-sync didn't work at first. Restarting atom did the trick.l

**Comment by elistone** [comment]
`remote sync config reload` is not a function found inside the code, _relatively new to the project_. I can only assume it was remove? or never existed.

Is config reload a feature being requested?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
