### ISSUE TITLE
Cannot find module 'fs-plus'

### ISSUE THREAD

**Issue by LibertyPaul** [yongkangchen/remote-sync#218]
I'm using atom 1.2.3, and I tried to install remote-plus by downloading it from repo as described in README:

...Download or clone this repository to your ~/.atom/packages/ directory...

But error appears: Cannot find module 'fs-plus'.
I know that it's dependency problem.
You should fix readme by adding dependencies.

P.S. I know that i can install it via apm, but I need offline way to do it.

**Comment by yongkangchen** [comment]
You can download or clone this repository, and enter the directory run `apm install`, then move the directory to your `~/.atom/packages/`
