### ISSUE TITLE
SCP to OSX doesn't work

### ISSUE THREAD

**Issue by shaynem** [yongkangchen/remote-sync#219]
Adding a OSX host to the SCP config doesn't login with username/password (Haven't tested with keys). It will return an Authentication failure - although logging in via terminal ssh works fine.

SCP to linux works fine.

Sublime SFTP plugin also works fine to OSX SSH host.

**Comment by juanmirocks** [comment]
It worked fine for me

**Comment by elistone** [comment]
@shaynem is this still an issue?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.

**Comment by siliconkibou** [comment]
Reopening issue, as I also have this issue.  MacOS/OSX host works fine in every other SFTP/SCP implementation using username/password but not Remote Sync.

UPDATE:  Had same error message in other SFTP plugins, but those plugins permitted the use of "keyboardInteractive" for password set to true, which once set, works just fine.  Does Remote-Sync have a similar mechanism?
