### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by nikitogr** [yongkangchen/remote-sync#223]
Providing a path, is it necessary? I usually connect to my ftp without providing a path.

For those who came here, please provide a path (target).

**Comment by nikitogr** [comment]
Alright fixed. I just added /www as a path. Also restarting the atom even with the bug box, seems to be the trick. Everything seems fine now.

**Comment by curtisforrester** [comment]
"path"? Path where. In the bash shell? In the JSON? And a path to what?

**Comment by m-jch** [comment]
When i run Upload file command this error happened.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Ubuntu 15.10
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0
**User**: root

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at FtpTransport.module.exports.FtpTransport.upload (/home/mohsen/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:38:27)
    at UploadListener.module.exports.UploadListener.uploadFile (/home/mohsen/.atom/packages/remote-sync/lib/UploadListener.coffee:31:15)
    at q.process (/usr/share/atom/resources/app.asar/node_modules/async/lib/async.js:769:21)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -0:03.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 remote-sync:upload-file (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete-html"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
clipboard-plus, v0.5.1
color-picker, v2.0.14
emmet, v2.3.17
file-icons, v1.6.13
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-blade, v0.16.0
linter, v1.11.3
linter-gcc, v0.5.7
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by m-jch** [comment]
When i add ```target``` property to ```.remote-sync.json``` file, this error has been fixed.

**Comment by GreenKi** [comment]
*If you already have a project folder created this can work with that one too.*
1. Create a project folder on the left pane.
2. Right click the folder and click configure.
3. Enter in the ftp/sftp/scp information as needed. *At the bottom right click save*
4. Edit your newly created `.remote-sync.json` file and replace `"transport": "scp"` with `  "transport": "scp",
  "target": ""`

**Comment by Jany-M** [comment]
I only have this problem now because I added this to my` .remote-sync.json `

```
  "watch": [
    "/assets/css/style.css"
  ],
```

Problem can only be fixed if I remove `watch`

**Comment by benjamingwynn** [comment]
I resolved this by appending `'target': '.'` to the end of my config
