### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by aydinkn** [yongkangchen/remote-sync#227]
Hi,
I have a folder named build (ignored by git) like this:
```
-build
--css
---font
----x.eot
----x.svg
----x.ttf
----x.woff
---x.css
---x.min.css
--js
---lang
----tr.js
----en.js
---x.js
---x.min.js
--x.html
```
build/css and subfolders uploaded but x.min.js not full upload (only a few bytes uploaded) and build/js subfolders and other files not upload. x.min.js size: 178803 bytes but uploaded x.min.js size: 131072 bytes.
js/lang subfolder and x.js not upload because x.min.js.
Additionally, when I reupload build folder, nothing happens. I need restart Atom editor.

**Comment by elistone** [comment]
@aydinkn I'm unsure how to even replicate this issue to even start working out what is going on, is there any more information you can have about this to help replicating the issue?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
