### ISSUE TITLE
duplicate uploads

### ISSUE THREAD

**Issue by nxet** [yongkangchen/remote-sync#230]
Not much of a bug rather a small detail which could be looked into. I just noticed that, when a file is open in more than a view in Atom (i.e. splitted right), the remote-sync uploads for each view on Save command.
Is it just me or has anyone else noticed this?

**Comment by elistone** [comment]
@nxet do you still have this issue?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
