### ISSUE TITLE
Can I connect with a remote server at Hostinger.es?

### ISSUE THREAD

**Issue by l222p** [yongkangchen/remote-sync#234]
I have the IP, user and password, but I have an error "Error: Timed out while waiting for handshake"

**Comment by elistone** [comment]
@l222p You should be able to to connect to any server, have you checked that your FTP details work using an FTP client?

**Comment by Jany-M** [comment]
@l222p I dont see why you shouldnt be able to? if your settings work with a ftp client, it should work fine with remote-sync too. Try using different `transport `method, if `ftp `fails.

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
