### ISSUE TITLE
`difftoolPath` should be `difftoolCommand` in settings

### ISSUE THREAD

**Issue by ant-fx** [yongkangchen/remote-sync#246]
The readme says:
> set difftoolPath in AtomSettingView of remote-sync — The path to your diff tool executable

The code however does not use the `difftoolPath` but instead uses the `difftoolCommand`

````
diffCmd = atom.config.get('remote-sync.difftoolCommand')
````

Maybe the readme could be updated to reflect this?

**Comment by yongkangchen** [comment]
You are right, thanks
