### ISSUE TITLE
open terminal failed: not a terminal 

### ISSUE THREAD

**Issue by franklioxygen** [yongkangchen/remote-sync#256]
Windows 10
[5:37:01 PM] Downloading all files: d:\Users\frank\Documents\projects
[5:37:03 PM] Download: open terminal failed: not a terminal to d:\Users\Users\frank\AppData\Local\atom\app-1.6.1\open terminal failed: not a terminal ...
Error: No such file

Mac OS got same issue

**Comment by yongkangchen** [comment]
Please provide me these information to help this issue:
* remote-sync version
* atom version
* which transport you use? FTP or SCP?

**Comment by franklioxygen** [comment]
remote-sync version  3.5.0
atom version 1.6.2
which transport you use? FTP or SCP? SCP/SFTP password auth

Destination is a Linux server, other SFTP tools works. 

Thank you

**Comment by yongkangchen** [comment]
Did you use tmux  on linux?

**Comment by franklioxygen** [comment]
yes, i did.
 looks need add -t flag or stop using tmux

**Comment by franklioxygen** [comment]
anyway I can use sshkey login, thank you
