### ISSUE TITLE
status and menu

### ISSUE THREAD

**Issue by yongkangchen** [yongkangchen/remote-sync#259]
> Hi
I’ve looked everywhere trying to find out to activate/toggle the view of the remote-sync status. When I first unchecked the Log status option it appeared at the bottom of the Atom editor pane. But if I click the “x” at the far right side of the status it goes away and stays away till I close and reopen Atom. I can not find a key binding or Cmd-Shift-P command to toggle this view. Your docs do not mention it at all.
Please make it clear and obvious.

> Please also put the remote-sync menu under the Packages top nav menu along with all the other packages that put their menus there. It’s a pain having to scroll up to the project root folder in the left sidebar and right-clicking to get to it.

> Please respond to these two requests.

from Bruce.Holm

**Comment by zicrox** [comment]
I don't know if "auto hiding log panel after transferring" it's implemented yet, but appear in commits.

**Comment by elistone** [comment]
This feature has now been implemented see #254 for more details.
