### ISSUE TITLE
split-diff as diff tool

### ISSUE THREAD

**Issue by popstas** [yongkangchen/remote-sync#260]
Can I use https://github.com/mupchrch/split-diff as diff tool?

**Comment by Jany-M** [comment]
Any input on what would be the right path+command syntax here?
Or if the existing setting allows for commands (eg. `split-diff:toggle`), for installed packages?

**Comment by popstas** [comment]
List of plugin commands of split-diff - https://github.com/mupchrch/split-diff/blob/master/lib/split-diff.coffee#L28

**Comment by Jany-M** [comment]
@popstas i have tried already. just need someone to confirm to what script to point to exactly and the right syntax to put in the remote-sync diff tools path.

**Comment by popstas** [comment]
@mupchrch, maybe you can help with integrate your plugin split-diff with remote-sync?

**Comment by mupchrch** [comment]
It looks like remote-sync calls the diff tool by [executing a child process](https://github.com/yongkangchen/remote-sync/blob/master/lib/RemoteSync.coffee#L224). I don't think it is possible to invoke a package from a child process, so I think split-diff would have to be specifically integrated into the package, much like [git-time-machine](https://github.com/littlebee/git-time-machine/blob/master/package.json#L28) does it.

I am not sure when I'd have the time to try the integration myself, so if anyone wanted to try, then they should check out how [this method](https://github.com/littlebee/git-time-machine/blob/master/lib/git-revision-view.coffee#L135) does it. And feel free to ask me questions!

**Comment by popstas** [comment]
@mupchrch, thank you for answer.

Sorry, I have not experience in CoffeeScript and have no time for implementing this method.
