### ISSUE TITLE
Monitoring File "Uncaught TypeError: Cannot read property 'parentNode' of null"

### ISSUE THREAD

**Issue by bendav91** [yongkangchen/remote-sync#262]
Noticed there is a problem with the first time you monitor a file. An error appears, seems to be fine after dismissing the error and expected behaviour resumes.

**Comment by elistone** [comment]
@yongkangchen @bendav91 I will look into this when I get home.

**Comment by elistone** [comment]
For anyone else getting this error, it's simply an issue with adding the monitoring style (possible on windows computers - needs more testing) and does not effect the monitoring functionality.

**Comment by acenkus** [comment]
I getting this error too. When I monitoring LESS compiled CSS

**Comment by elistone** [comment]
@acenkus @bendav91 @yongkangchen A PR has been made which should resolve this it just needs to be merged then pushed.

**Comment by acenkus** [comment]
@elistone , Yep! It works! Thank you ;)
