### ISSUE TITLE
Custom file monitoring (eg. upon .less compile, upload both .less and .css)

### ISSUE THREAD

**Issue by Jany-M** [yongkangchen/remote-sync#269]
I was wondering if it was possible to flag a file (eg. // monitor: style.css) so that when it gets saved, the monitor file gets uploaded too (if auto-upload is checked)?
If not, would you consider adding this feature?

I personally use [this ](https://atom.io/packages/less-autocompile)atom less-autocompile package, in case it's any help.

Thank you for this package, love it :+1:

**Comment by elistone** [comment]
What version are you using?

Using the latest version 4.0.1 this is possible right click a file and select `Monitor file`

**Comment by Jany-M** [comment]
@elistone great! sorry I missed that (is it mentioned anywhere?).

For anyone needing the same thing: in the tree view, right click on the .css (in this case), it will be uploaded as soon as the .less file is compiled.

**Comment by elistone** [comment]
@Jany-M It is on the readme.md `Monitoring files for external change and automatically upload` but maybe not that obvious. It was only put in a few days ago, so there is room for improvement.

PR #261 & #264 have a few more details for example:

The ability to list all monitored: <kbd>cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and find `Remote Sync: Mointor Files List`

**Comment by enoversum** [comment]
@yongkangchen Thanks for implementing it, real sweet it is finally there :cupid: ! 
Would it somehow be possible to pre-define on a project basis which files should be generally watched for changes? That would save a few clicks every time you open up a project and would normally have to right-click the file(s) and pick the desired option :smiley: .

**Comment by elistone** [comment]
@enoversum as the creator of the monitoring PR I can look into adding this feature for @yongkangchen not sure when I will get around to it but should be in the next few weeks.

**Comment by enoversum** [comment]
@elistone Oh well, that sounds lovely! Since I am not able to code as much, I won’t be of much help, but if I can help with anything, still, just let me know :wink: .

**Comment by elistone** [comment]
@enoversum just so you know I started the creation of 'watching based on config' on [my fork](https://github.com/elistone/remote-sync/tree/monitor-file) generally it works, but there a few issues still to solve to make it almost perfect for every scenario.

**Comment by enoversum** [comment]
@elistone Oh well, that sounds really great (didn’t expect you to work on it for weeks, as far as your comment hinted at :wink: )! I’ll happily leave you in peace in order to fulfill wonders, haha :).

**Comment by dallanlee** [comment]
+1 For using the config to define monitored files beforehand. This is what I was looking for.

**Comment by enoversum** [comment]
@dallanlee Yeah, it will be super comfortable since you define it once and forget about it^^.

**Comment by elistone** [comment]
@dallanlee @enoversum give me around an hour an there should be a PR 📦

**Comment by enoversum** [comment]
@elistone Haha, yes :smile: !

**Comment by dallanlee** [comment]
Excellent @elistone

**Comment by elistone** [comment]
Done see #275
