### ISSUE TITLE
Ignore paths download even though they are ignored

### ISSUE THREAD

**Issue by as3k** [yongkangchen/remote-sync#274]
This is a huge problem for me as I do not need all the files that are in my node directories that I have on remote server and when I explicitly say that i do not want a directory included in my download and it is pulled down anyway. Is there a way to fix this?

**Comment by Jany-M** [comment]
Same here. Using `remote-sync 4.1.2`, Win10 64x.
Ignored folders are still downloaded, when using the Download Folder on tree view right click.

**Comment by gymbo97** [comment]
Same Problem on OS X 10.11.4 with version 4.1.2 downloads folders even if they are in the ignore Array.

**Comment by Fije** [comment]
Is this issue still open?

**Comment by as3k** [comment]
Closed this issue due to age. Not sure if it was ever resolved.

**Comment by incolas** [comment]
From personal experience, I'd say it was not.  ^^
