### ISSUE TITLE
Possible to use ~/.ssh/config entrie for connection 

### ISSUE THREAD

**Issue by janiroquai** [yongkangchen/remote-sync#276]
It would be great if plugin would work with the .ssh/config file in home directory (I'm on OSX, but should be similar in other OS – hopefully). This is also for security reasons (I'm not happy with passphrase in plain text).

In Mac Terminal I only have to enter e.g.
`ssh myServer`

All settings and credentials (like keyfile) are defined in .ssh/config file. Key-Passphrase in handled by OSX keychain.

Thanks for this cool plugin!

**Comment by elistone** [comment]
There is an issue open for this, see #152 and give it a thumbs up.
Closing.
