### ISSUE TITLE
Remote-Sync overwrite newer files.

### ISSUE THREAD

**Issue by tiger2380** [yongkangchen/remote-sync#286]
I make changes in one editor, save it and make changes in Atom and save it, remote-sync will overwrite the changes that I make in the first editor. 

Is there a way I can monitor changes in my remote files before upload?
Thanks.

**Comment by elistone** [comment]
This sounds more like something to do with atom core? Are you implying when you change information in a file the changes do not get displayed in atom? There for overwriting changes?

Can I also add why are you using two diffrent editors?

**Comment by tiger2380** [comment]
Sorry, I should had been clearer. At my job, I'm working on a web app. We are not using GIT so we are all working in the same project folder. The files are on a network drive. When I map to the network drive using Atom, Atom becomes very slow and sometimes unresponsive because the project is pretty big.

So I decided to FTP to the project. Before I start using FTP to sync my work with the project, I like to make sure that my editor will not overwrite newer remote files. So I use an another editor to make changes to a remote file, save the changes and use Atom(Remote-Sync) to make changes to that exactly file, save my changes to see if I'll get a prompt or something that will let me know that the file that I'm about to write to, is newer/modified.

I hope that clarify my issue up some.

**Comment by elistone** [comment]
How exactly is this related to remote-sync as you have said 

> remote-sync will overwrite the changes that I make

I'm still a bit confused as to how remote-sync is overwriting it, you save in 1st editor and you check file in 2nd editor (atom) and the file is correct? Then you upload your file and remote-sync overwrites the 1st editors changes?

Sorry If I'm missing something but I feel like saving a file in 1 editor should be the same in the 2nd editor & am confused where remote-sync comes in.

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
