### ISSUE TITLE
High processor usage on OSX

### ISSUE THREAD

**Issue by djaddo** [yongkangchen/remote-sync#287]
Hi, 
First of all, I want to thank you for this great extension. It helps a lot! 
But, seems that I have a problem with it. 

As you can see at [this link](http://screencast.com/t/zZLj5HseG), the extension causes a really high processor usage on my MacBook Pro.

I have tried to disable other extensions but nothing happened, until I disabled RemoteSync.

A few seconds after disabling it [this happened](http://screencast.com/t/QwX4xZFpPTr).

Processor usage dropped from 87,4% to 1,4%, so looks like the extension uses 86% of my i5 2,3GHz.

It would be great if you could help in solving the issue.

I do really like the extension and I would like to continue using it, but I'm not able until I fix the issue.

Thanks in advance,
Adnan

**Comment by elistone** [comment]
This will be hard for me to fix as I do not have the same issues, but I can talk you though possible places that could be causing it.

to try and narrow it down I will need a little more information about what you were doing when getting a high processor, was remote-sync 'idle', monitoring files, uploading files, downloading files or anything else you can think of?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
