### ISSUE TITLE
Major Issue, plugin does not work even on clean install of Atom

### ISSUE THREAD

**Issue by matt3224** [yongkangchen/remote-sync#289]
I am receiving the following message: "Error: Timed out while waiting for handshake"

I have double checked my settings, using sftp and password. I get this error every time.

![screen shot 2016-06-07 at 10 02 56](https://cloud.githubusercontent.com/assets/2401925/15851936/0bb68d5a-2c97-11e6-813c-2fa80f574730.png)

Can this be fixed asap please,
Thanks

**Comment by elistone** [comment]
@matt3224 I have just done a fresh install today (clean install on windows 10) and did not see this issue.

Could you please give some more details such as OS, and what you were trying to do.

**Comment by matt3224** [comment]
Hi @elistone,

I have a 27" iMac 2010 running OSX 10.11.5, Atom 1.8.0, remote-sync 4.1.2

I also do not have any other community packages installed.

I installed Atom fresh on my iMac today and the first package I installed was remote-sync. I added a local project and entered the server credentials (which I have triple checked and work successfully in Coda), along with the remote path. I then opened a local file and tried to save, which presented me with the above error.

Do you need any other information?

Thanks,

**Comment by elistone** [comment]
@matt3224 thanks for the quick reply, last thing what type of server details e.g. ftp/sftp with or without key.

**Comment by matt3224** [comment]
sftp with password

**Comment by elistone** [comment]
I believe there is an issue open for this, see #185 and give it a thumbs up.
Closing for now.

**Comment by matt3224** [comment]
Its almost a year old and has been marked as a question??
