### ISSUE TITLE
Write another user mode to fix Permissions Fail

### ISSUE THREAD

**Issue by AdsonCicilioti** [yongkangchen/remote-sync#296]
At the level of doubt and also suggestion, I wonder if there is the possibility to spend some instruction for writing files via SCP be made by a particular user as the `www-data`, to fix the failure error permission.

The fact is that my access user server is called `ubuntu`, but permission policies and with the directory owner is www-data.

I think not to make any trick to be changing the directory permissions policies, but seek some solution to scribe the transfer with the same permissions.

*It is possible to spend some instruction by remote-sync or have to change my policy permission on the server?*

**Comment by elistone** [comment]
I'm unsure of what you are asking of the remote sync module.
