### ISSUE TITLE
ignore folder

### ISSUE THREAD

**Issue by ozanuzer** [yongkangchen/remote-sync#297]
Hello, 

I currently use remote ftp plugin on atom. Can you add ignore folders. We can ignore only files. 

Thank you.

**Comment by AdrienCS** [comment]
**+1**

**Comment by elistone** [comment]
Ignore uses an `Array of [minimatch](https://github.com/isaacs/minimatch) patterns of files to ignore` which means you can ignore a whole folder using something like: `my_folder/**`

**Comment by ozanuzer** [comment]
Hello,

It is still downloading or uploading. 

Config file like this;
{
  "transport": "ftp",
  "uploadOnSave": true,
  "useAtomicWrites": false,
  "deleteLocal": false,
  "ignore": [
    ".remote-sync.json",
    "destek/**",
    "yedek/**"
  ],
  "watch": [],
  "hostname": "***.net",
  "target": "/public_html/project",
  "username": "***",
  "password": "***"
}

destek and yedek are folder. Am I doing wrong something?

**Comment by elistone** [comment]
@ozanuzer to ignore everything inside the folder add `/**`

**Comment by ozanuzer** [comment]
@elistone already added /**. It's like "yedek/**". Is it wrong? If it's true then it is still downloading ignored folders.

**Comment by elistone** [comment]
@ozanuzer ah downloading ignored files, sorry I thought you said uploading there seems to be a bug with it downloading ignored folders see #274, not had any chance to look into this yet.
