### ISSUE TITLE
Error: Permission denied

### ISSUE THREAD

**Issue by yongkangchen** [yongkangchen/remote-sync#303]
Issue from my mail send by Stephen Johnson
---------
I wasn't sure where I could leave a question or message you so this is the best I could find. I recently used your remote-sync package for atom.io to connect to my raspberry pi 3 via ssh. It looked like it was running great and it seems to have gotten all of the files (and more that I didn't know where on the pi, like save files) but then I got an error that said "Error: Permission denied".
Below is a screen shot of what the error read.

![unnamed](https://cloud.githubusercontent.com/assets/704762/16825046/a824b8be-49a3-11e6-8375-83d83a2f59a8.png)

I'm not sure what the problem is because I'm pretty confident that I filled out the configuration correctly. I doubt that it would get this far if I didn't. If there's any guidance you can give, it would be much appreciated.

Thank you!

**Comment by yongkangchen** [comment]
Please provide me these information to help this issue:
* remote-sync version
* atom version
* which transport you use? FTP or SCP?

**Comment by RockScar253** [comment]
I have version 4.1.2 of remote sync, version 1.8.0 of Atom, and remote sync is set to SCP/SFTP at the moment.

**Comment by elistone** [comment]
I think this is going to be a tricky one to debug due to the relatively little information as to why permission is denied.

Could you try turning on `log to console` found in the settings of package and update if that gives anymore information.

**Comment by RockScar253** [comment]
I have decided to simply wire into my pi via USB or upload files too and from it with a flash drive. SSH connection was just something cool I wanted to try but I don't have much time on this program to try and debug this. Thank you all for your willingness to help though! If I find that I have more time than I expected, I may come back and try again in which case I will `log to console` and let you know what it gives.

**Comment by elistone** [comment]
Okay great I will reopen the ticket when you come back.
