### ISSUE TITLE
Cannot upload or download a directory in sftp with 'ChrootDirectory'

### ISSUE THREAD

**Issue by zealseeker** [yongkangchen/remote-sync#305]
I created a "ChrootDirectory" user, for example test1
so `/home/test1` will be `/` when the user login in with sftp.
with FileZilla, I can login and upload/download anything like:
Create a folder named 'aa' and a file 'bb' as `/aa/bb` (real path is `/home/test1/aa/bb`)
Create a file 'cc' as `/cc` (real path is `/home/test1/cc`)

But when I configured remote_sync as the target was set as `/`, I could not download the whole folder (`/`) Even I created locally a folder named aa, I still cannot upload or download the folder.
BTW, I can upload a file named cc if it existed in the local directory.

So I conclude that:
I can only upload (or download if it existed) a file in the root directory.
I cannot upload (or download if it existed) a folder in the root directory.
I cannot upload (or download if it existed) a file in a sub directory other than root directory (like `/aa/bb`)

The only Error information is "Error: No such file"

```
Error: No such file
[15:27:20] Downloading all files: /Users/**/Documents/temp/test
[15:27:20] Connecting: test1@**
[15:27:21] Download: This service allows sftp connections only. to /Users/**/Documents/temp/test/This service allows sftp connections only. ...
Error: No such file
```

To make sure it was not caused by 'root' (The root directory should be owned by root to 'ChRootDirectory' ), I created a folder named 'aa' and set the target as '/aa'. The problem still existed:
I can upload `/aa/bb.txt` but not `/aa/bb/cc.txt` whatever the folder bb existed in local or remote server.

**Comment by bart1970** [comment]
Had the same problem, and removed: ForceCommand internal-sftp
Afterwards I did no longer get the message that the service only allows sftp connections.
But still no downloads/uploads of folders. Only works for files.
