### ISSUE TITLE
minimatch is outdated and matchBase issue

### ISSUE THREAD

**Issue by kambing86** [yongkangchen/remote-sync#308]
for the ignore option:
I want to ignore all the files under the root folder ONLY, but the matchBase: true will ignore all the files in other folders if I use "*", and there is no way to ignore all the files under the root folder ONLY.

**Comment by elistone** [comment]
Looking at your PR #309 I think it would be better to add a flag / option instead of removing it, otherwise  doing the opposite to your request will not be possible.

**Comment by kambing86** [comment]
that's totally possible by using "Globstar" ** matching

**Comment by elistone** [comment]
Ah alright then, closing this ticket and will try and merge the PR soon. Thanks @kambing86
