### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by karimcossutti** [yongkangchen/remote-sync#310]
Hello,
Is it possible to bind remote sync actions to keyboard shortcuts? if so how?

For exemple i'l like to bind cmd+alt+u to upload the current file i'm editing.

**Comment by elistone** [comment]
Hi @karimcossutti currently there are no default keyboard shortcuts built into remote sync however you can set one up manually doing the following:

Go to settings > Keybindings (on the left)
Clicking `your keymap file` will open up your custom keymap file

and pasting the following bellow all the comments:

```

'atom-workspace':
  'cmd-alt-u': 'remote-sync:upload-file'

```

This creates a keybinding to be used in the workspace that will active the uploading of a file function.

I do think adding a few default keyboard shortcuts would be a nice touch so I'm keeping this ticket open for that.
