### ISSUE TITLE
Error: All Configured Authentication Methods Failed

### ISSUE THREAD

**Issue by pcwa-ahendricks** [yongkangchen/remote-sync#326]
remote-sync worked fine until as of lately.  I've made no config changes in my project since the time it was working.  I'm using a Mac, macOS Sierra.  I'll point out that if I open a terminal i can ssh into the server with my ssh key and without having to use my key passphrase, so i believe ssh-agent is running without any problems.  

Using remote-sync 4.1.4

My configuration is as follows.

``` javascript
{
  "transport": "scp",
  "hostname": "host.name.net",
  "port": "22",
  "username": "administrator",
  "useAgent": true,
  "target": "/valid/path",
  "ignore": [
    ".remote-sync.json",
    ".DS_Store",
    ".git/**"
  ],
  "uploadOnSave": true,
  "useAtomicWrites": false,
  "deleteLocal": false,
  "watch": []
}
```

**Comment by essell** [comment]
I can confirm the same issue here. Configging useAgent to true returns the same error. The environment variable SSH_AUTH_SOCK is set and points to the socket for ssh-agent.

**Comment by skrzepij** [comment]
Same problem here.
my config: 
`{
  "uploadOnSave": true,
  "deleteLocal": true,
  "hostname": "192.168.1.1",
  "target": "/var/www/project_folder/public_html",
  "ignore": [
    "/venv/**",
    ".svn",
    ".hg/**",
    ".git/**",
    "**/.git/**",
    ".bzr",
    "_darcs",
    "CVS",
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    "tmp",
    "log",
    "**/node_modules/**",
    "Oldskel/**",
    "**/vendors/**",
    "**/wflogs/config.php",
    ".remote-sync.json",
    ".tmp/**",
    "/wp-admin/**",
    "/wp-includes/**"
  ],
  "username": "username",
  "transport": "scp",
  "port": "37",
  "useAtomicWrites": false,
  "watch": [],
  "keyfile": "/Users/Sniffer/.ssh/id_dsa",
  "passphrase": "SomePassword"
}
`

This config was working fine while connecting to other VPS. But when I try to connect with my local dev server (Odroid with Ubuntu 16.04.1 LTS) there is no way to connect using my ssh key, and have no idea why. 
When I change login method from privatekey to password (in config) its working fine.

**Comment by pcwa-ahendricks** [comment]
@essell could be right. I'm having similar issues with other popular atom packages that use ssh2, namely [remote-ftp](https://github.com/mgrenier/remote-ftp).

**Comment by pcwa-ahendricks** [comment]
All of a sudden this is working again.  Not sure what the issue is. I opened this ticket so I will go ahead a close it.

**Comment by devcline** [comment]
remote ftp and remote sync is giving me a error 

```
[19:48:23] Connecting: xxxx@xxxx:22
Error: All configured authentication methods failed
```
all configuration is working in winscp fine.
Server Side: 
```
Dec  4 19:47:48 war sshd[28404]: Received disconnect from xxxx port 7755:11:  [preauth]
Dec  4 19:47:48 war sshd[28404]: Disconnected from xxxx port 7755 [preauth]
```
how to invistigate ? any clues ? thanks

**Comment by Bengreen** [comment]
any update on this. I am having the issue and strangely auth seems to work fine when downloading, but getting auth errors when uploading.

**Comment by Shardy153** [comment]
I do not need an SSH key or password to SSH into a remote VM. Can anybody tell me how to use remote-sync in such a case? The VM is behind VPN and I am connected to VPN but still, I am getting the same error. I tried the key and the path empty, I tried with a password and kept the password field empty, then I tried useAgent. But none of those works. I can confirm that I am able to SSH from the terminal.
Please help.
