### ISSUE TITLE
Possibe to add "Connect/Disconnect" option ?

### ISSUE THREAD

**Issue by marcoczen** [yongkangchen/remote-sync#344]
Hi,

remote-sync is currently mry preferred remote editing option via sftp. I like the window at the bottom of the editor which shows the upload / download progress.

Is it possible to add a;

 "Connect To Remote Host"
"Disconnect to Remote Host"
option when we rightclick on the project folder ?

This will help when the connection freezes - we have to close / open atom editor to get a connection.

**Comment by joshuairl** [comment]
Even if there was just a term button to kill the current process... would be ideal to have some way to just stop it.

![image](https://cloud.githubusercontent.com/assets/171077/21817709/1216a508-d733-11e6-9007-16f7fe6adb10.png)

**Comment by marcoczen** [comment]
Is this project abandoned ?

**Comment by marcoczen** [comment]
Looks like it. Hope it gets revived.
