### ISSUE TITLE
Menu in tree view disappear in Atom 1.17.0

### ISSUE THREAD

**Issue by levythu** [yongkangchen/remote-sync#399]
As title, after upgrading Atom 1.17.0, I cannot find remoteSync menu in tree view anymore and it's hard to sync a folder

**Comment by jamiewoods-uwd** [comment]
See this comment for permanent fix pending update: https://github.com/yongkangchen/remote-sync/issues/388#issuecomment-302121984

**Comment by daverickdunn** [comment]
The missing context menu has been patched and is working with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
