### ISSUE TITLE
Right click menu "Remote-sync" not available

### ISSUE THREAD

**Issue by vlietvankevin** [yongkangchen/remote-sync#401]
Hi Remote-sync,

On right click on a project folder or a file i can't go to "remote-sync" because it's not available in the menu anymore.

Kind regards

Kevin

**Comment by Jany-M** [comment]
Already addressed [here](https://github.com/yongkangchen/remote-sync/issues/388#issuecomment-302121984).

**Comment by daverickdunn** [comment]
The missing context menu has been patched and is working with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
