### ISSUE TITLE
Feature doubt

### ISSUE THREAD

**Issue by edgarcosta92** [yongkangchen/remote-sync#403]
Hi all,

There is a feature in which if you erase a file from the remote it will do the same in local.  How can we do the oposite ? Erase locally and remove it remotely.

**Comment by daverickdunn** [comment]
1. Do this:

![image](https://user-images.githubusercontent.com/7645242/32058211-56a8c540-ba61-11e7-81d2-fff79a337d2e.png)

2. Delete File.
