### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by JohnSlaughter** [yongkangchen/remote-sync#404]
I see there are issues, and I see that there a few pull requests addressing those issues, but not a word from the developer in like 7 months?  Can someone else fork this and roll in all the patches so we can publish a version that is not abandoned?

**Comment by Wingysam** [comment]
This is what I was wondering. Also, this issue should have been about something missing, as it's #404 :P

**Comment by JohnSlaughter** [comment]
404 - DEVELOPER NOT FOUND!

**Comment by laymance** [comment]
I'm thinking about forking it, fixing and re-publishing... any ideas for names of the package, and is anyone interested in helping to maintain it going forward?

**Comment by laymance** [comment]
I should mention that this package is too critical for my workflow for it to stop working and/or become abandonware.

**Comment by laymance** [comment]
Ok - I have forked the project and published a new plugin.  It is called "remote-sync-pro".  To install you should uninstall remote-sync first then search for the remote-sync-pro package and install.  I've added several fixes for the outstanding issues, with more changes to come.  Right now I need people to test it.

There is a **known possible issue** that I'm seeing randomly, and it has to do with a 3rd party extension (dependency).  I'll keep looking for a fix but it may not be fully fixed until they fix it up stream.  There is a workaround however.  If you install and nothing seems to work, look in the status bar at the bottom of Atom for a red "bug" icon.  Click this icon and it will give you a message about native modules being compiled for an older version of Atom.  At the upper right will be a "Rebuild Packages" button.  Click this button, it will rebuild, then everything should work fine.

If you can test out the new package and file any issues there (not here) - https://github.com/laymance/remote-sync-pro

**Comment by daverickdunn** [comment]
I've been added as a collaborator and will try address any major bugs. Pull requests are welcome. A new patch has been released today for the context menu issue: https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
