### ISSUE TITLE
No menuoption in treeview on atom1.17.2

### ISSUE THREAD

**Issue by newnix123** [yongkangchen/remote-sync#410]
![image](https://cloud.githubusercontent.com/assets/7959136/26781660/4c454d3a-4a22-11e7-9341-ff292c2ed60d.png)

**Comment by linuxbastard** [comment]
Can confirm that menu tree option is not available in 1.17.2.

**Comment by therealcybernomad** [comment]
Still broken in Atom 1.18 beta 1

**Comment by nickyreinert** [comment]
Hotfix can be found here (fixes the issue on 1.17.2)

https://github.com/yongkangchen/remote-sync/issues/388#issuecomment-302121984

**Comment by gitmq** [comment]
Confirming that the above referenced hotfix works for Atom 1.18.0 x64, Win 7

**Comment by daverickdunn** [comment]
The missing context menu has been patched and is working with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
