### ISSUE TITLE
什么时候修复tree-view右键菜单问题?

### ISSUE THREAD

**Issue by newnix123** [yongkangchen/remote-sync#411]
在atom最新版上，tree-view右键菜单里找不到romote-sync选项
@yongkangchen

**Comment by daverickdunn** [comment]
The missing context menu has been patched and is working with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
