### ISSUE TITLE
[Closed - Not Solved ] Atom Editor - Remote Sync Hangs After Some Time

### ISSUE THREAD

**Issue by marcoczen** [yongkangchen/remote-sync#413]
Hi, Remote Sync Hangs After Some Time - say maybe 10hours +, U have to shutdown atom and open it again before Upload FIle Option works. Using the latest version of Remote SYnc.

**Comment by marcoczen** [comment]
No response ?
Is this project abandoned ?

**Comment by daverickdunn** [comment]
This is likely a timeout that could occur at any point along the connection. Try extending your keep alive settings on your server. ClientAliveInterval, ClientAliveCountMax, TCPKeepAlive, etc.
