### ISSUE TITLE
Unable to use remote-sync package on my Mac, to access/edit/sync my files remotely

### ISSUE THREAD

**Issue by prashant3-yishu** [yongkangchen/remote-sync#416]
I'm following https://atom.io/packages/remote-sync to setup, but I don't see the option of "Remote Sync" when I right click on main project folder. This blocks me to proceed further. I want to sync my files using scp only since ftp is not supported on my server.

MacOS Sierra
Version: 10.12.5 (16F73)

**Comment by prashant3-yishu** [comment]
![screen shot 2017-06-13 at 1 00 55 pm](https://user-images.githubusercontent.com/3317012/27101965-67818250-5038-11e7-9b82-b436f6d1313d.png)

**Comment by Cam** [comment]
Same issue for me.

**Comment by NECKRHINOS** [comment]
Same for me, I cannot access the Remote Sync dialogue on my Mac anymore. Guess it happened after updating Atom to version 1.18.0. OSX is version 10.12.5 as well

**Comment by joshuahaber** [comment]
Same here :(

**Comment by jodacame** [comment]
same for me, I can't see remote sync on my menu (Right click over folder)

**Comment by nanthan** [comment]
Same for me :(

**Comment by upggr** [comment]
same here

**Comment by mcharris** [comment]
Do you have a red bug symbol in the bottom right? If so click on that and see whats going on. It might be possible to just rebuild it. In that same window click the rebuild button.

**Comment by joshuahaber** [comment]
I don't have that, but it doesn't work anymore.  Luckily the save -> upload feature still works.  I can't sync one file or even configure it anymore it seems.

**Comment by maertz** [comment]
Following worked for me (OSX 10.12.5), still have no context menu to choose from, though.

- Rebuilt the package if needed within your package list detail page "Packages / Remote Sync"
- Manually create ".remote-sync.json" within your folder
- Open any file within your project
- Use cmd + shift + p -> "Remote Sync: ..." to do your stuff

**Comment by pengyan518** [comment]
same here

**Comment by daverickdunn** [comment]
The missing context menu has been patched and is working with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
