### ISSUE TITLE
Allow using variables in Config File Name

### ISSUE THREAD

**Issue by rgawenda** [yongkangchen/remote-sync#421]
Using templates in this field, as {project-name}, would allow to use the package without storing files (with sensitive info) in the project, for those who work in a team.

**Comment by daverickdunn** [comment]
Hi there, you can already achieve this in one of several ways (assuming you're looking to hide passwords).

1. Use public-private key authentication. This can be configured to use a default folder, or at the very least each user can update it to point to their key, thus not exposing sensitive information.

2. By extension, you could set the useAgent field to **true** to use the systems SSH agent, thus requiring no changes to .remote-sync.json by other team members. Assuming an agent is installed and the keys are added.

These next two assume you are using git for version control:

3. Not sure if this is a good idea, or even really works, but you could attempt to commit an initial template and then ignore it thereafter using `git update-index --assume-unchanged <file>`. Though I think this may only work on your local repo.

4. What I have done in the past, when it wasn't really worth the time setting up SSH (which isn't hard, I'm just lazy), is to commit a file called `.remote-sync.json.template` with all the configuration **except** for the username and password. Then I set a rule in `.gitignore` for my personalised `remote-sync.json`. Each user can then make a copy this file after checking out and safely add their own username and pass. This of course requires maintenance of two files, but really, it's generally a one-off setup with the odd addition to the watch list.
