### ISSUE TITLE
the package is installing but cannot be found anywhere

### ISSUE THREAD

**Issue by Theog75** [yongkangchen/remote-sync#426]
After I install the package i can configure it but it cannot be used at all - I cannot find it in the packages menu at the top nor can I find the remote->configure option when I click a project folder.

Please help.

**Comment by simplynutty** [comment]
I've come across a similar issue in that I can't find remote sync in any of the menus so I can't configure it.  I'll poke around more and report back.

**Comment by gitmq** [comment]
I noticed this problem for the past few weeks also.  A hotfix can be found below:
#388 @dtsdev

Confirmed working for:
Atom 1.18.0 x64
remote-sync 4.1.5
Win7

**Comment by BadMoodTaylor** [comment]
Same here.

My previously configured project folders will still upload on save as normal.  I cannot find remote sync options when right clicking a project folder or in any menu.  So I don't see how I can configure new project folders.

**Comment by simplynutty** [comment]
The fix mentioned by @gitmq ^^ restored the menu for me.  It seems like remote-sync hangs or slows Atom down at times though it could be some other plugin as well.

**Comment by BadMoodTaylor** [comment]
Wow I must be going blind because I didn't see that the first time.  Got it working!  Thanks for that quick reply @simplynutty !!!

**Comment by daverickdunn** [comment]
The missing context menu has been patched, works with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
