### ISSUE TITLE
Completely Broken, no longer works.

### ISSUE THREAD

**Issue by timothymarois** [yongkangchen/remote-sync#427]
Even after the quick fix listed here #388 this at least gave the menu options back, but nothing else works, such as uploads, even connecting. its completely useless at this time.

**Comment by nickskitch** [comment]
open context.cson (.atom/packages/remote-sync/menus) and change the following lines:

line 2: from 'atom-text-editor, .tree-view.full-menu .file':[ to 'atom-text-editor, .tool-panel.tree-view .file':[
line 13: from '.tree-view.full-menu .header.list-item':[ to '.tool-panel.tree-view .header.list-item':[
Restart Atom, done.

**Comment by nickskitch** [comment]
Seems to be a dead abandoned project with nobody stepping up to fix it.

There are a few of these types of plugins available but none of them seem to work.  Has anyone jumped ship from this plugin and found one that replaces this?

**Comment by timothymarois** [comment]
@nickskitch Yeah same with me. There are a few good ones, esp with file tree access, and none are working anymore. Looks like the death of FTP is on the way....

**Comment by ionutzp** [comment]
💀

**Comment by laymance** [comment]
I've been kicking around the idea of forking this project and updating it up for a while now.  As I said in another thread, this plugin is much too important to my workflow for it to go away... in fact, without this plugin I would most likely have to switch to another editor all together.  

Up until this point I've been patching my copy locally to keep things going.

It will be early next week before I can fork it and get things going.  All of the bug fixes will need to be applied, etc.  Just have to figure out what to call the plugin, I wish the owner of this repo would just allow me to take it over, but he seems to be MIA.

**Comment by laymance** [comment]
Ok - I have forked the project and published a new plugin.  It is called "remote-sync-pro".  To install you should uninstall remote-sync first then search for the remote-sync-pro package and install.  I've added several fixes for the outstanding issues, with more changes to come.  Right now I need people to test it.

There is a **known possible issue** that I'm seeing randomly, and it has to do with a 3rd party extension (dependency).  I'll keep looking for a fix but it may not be fully fixed until they fix it up stream.  There is a workaround however.  If you install and nothing seems to work, look in the status bar at the bottom of Atom for a red "bug" icon.  Click this icon and it will give you a message about native modules being compiled for an older version of Atom.  At the upper right will be a "Rebuild Packages" button.  Click this button, it will rebuild, then everything should work fine.

If you can test out the new package and file any issues there (not here) - https://github.com/laymance/remote-sync-pro

**Comment by creategui** [comment]
@laymance I wrote an email to the current owner about adding someone else or transferring this project.  He responded today asking for a suggestion.  Would you be interested?  I know you just forked the project.  Thoughts?

**Comment by laymance** [comment]
@creategui I would be ok with that.  There are 100k+ users on remote-sync, it would make more sense if we could take it over other than start from scratch.

**Comment by creategui** [comment]
@laymance I gave him your name a couple days ago.  Has he contacted you?  I emailed him at the address in his github profile.

**Comment by laymance** [comment]
@creategui No he hasn't contacted me yet.  I'll reach out to him later this evening.

**Comment by daverickdunn** [comment]
New release https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69 tested without issue.
