### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by cipixul** [yongkangchen/remote-sync#431]
It installs but doesn't show anywhere, I can't find it and I can't set it up. No error, no nothing.

I use windows 10 on this machine.

**Comment by matheod** [comment]
Same.

**Comment by sergio101** [comment]
I am having the same problem on MacOS..

**Comment by bok04** [comment]
Same issue. I've upgraded to Atom 1.19.0, so wondering if this version breaks the plugin.

**Comment by matheod** [comment]
See https://github.com/laymance/remote-sync-pro

**Comment by cipixul** [comment]
This site is the github site of the plugin, where is the solution?

**Comment by daverogers** [comment]
The original dev of remote-sync abandoned it. matheod forked it and applied fixes. Install that one instead.

**Comment by cipixul** [comment]
Thanks for update. I moved on though...

**Comment by matheod** [comment]
(I am not the one who forked it)

**Comment by daverickdunn** [comment]
There's an open issue with a hotfix here: https://github.com/yongkangchen/remote-sync/issues/433

This issue gives the appearance of remote-sync not working, but actually it's just the context menu that's not showing, auto-saving, etc. works fine.

Expect an update in the following few days.
