### ISSUE TITLE
Package maintainer MIA

### ISSUE THREAD

**Issue by chbrules** [yongkangchen/remote-sync#436]
Seems this package is abandoned now. How long has it been to fix this thing to working status?

**Comment by dessant** [comment]
@chbrules, if you need a solution now, this is a working fork:
https://github.com/laymance/remote-sync-pro

**Comment by daverickdunn** [comment]
I've been added to the collaborators and will try to address major bugs over time,. The missing context menu has been patched and is working with Atom 1.21 and Atom IDE (1.22...?): https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69

If you have specific issues, or even better, pull requests, please fire away.
