### ISSUE TITLE
"Remote Sync" not appearing after right click.

### ISSUE THREAD

**Issue by andrewtoups** [yongkangchen/remote-sync#440]
When I select my project folder, "Remote Sync" is not appearing in the context menu.

Using 1.20.1 on Mavericks.

**Comment by aidanranney** [comment]
I am also having this same issue.
Atom v. 1.20.1 on El Capitan

Hi toups! #SB

**Comment by eastonYi** [comment]
use the commend with keybinding `ctrl+shift+p` and input `remote`

**Comment by DimitryDushkin** [comment]
No "remote" thing in ctrl+shift+p menu.

**Comment by DimitryDushkin** [comment]
I had incomplete packages issue (look at bug icon at bottom left). Rebuilding packages helped.

**Comment by daverickdunn** [comment]
For a hot-fix see issue: https://github.com/yongkangchen/remote-sync/issues/433

Remote-sync _is working_, it's just not appearing in the project menu...

**Comment by daverickdunn** [comment]
Duplicate of https://github.com/yongkangchen/remote-sync/issues/433

Will patch in the coming days.
