### ISSUE TITLE
After Atom upgrade to 1.21.0 Remote sync menu options not working

### ISSUE THREAD

**Issue by Om1986** [yongkangchen/remote-sync#443]
Today after upgrade to atom version 1.21.0, remote-sync stopped working. Right click is showing menu options but click on the options like Configure, Upload folder not working.
I had enable auto-save in my remote-sync.json and that is also not working. Can somebody please post a hot fix for this ?

**Comment by chrisduong** [comment]
me too

**Comment by daverickdunn** [comment]
Duplicate of https://github.com/yongkangchen/remote-sync/issues/433

Hotfix provided in that link.

Will patch in the coming days.
