### ISSUE TITLE
Remote Sync context menu only appears on subfolders/files

### ISSUE THREAD

**Issue by tdonohue** [yongkangchen/remote-sync#448]
Environment: Atom v1.21.1 with RemoteSync v4.1.6 on Windows 10

While the latest release of RemoteSync claims to fix issues like #401, the right-click context menu still doesn't appear on the top-level project folder. But, now, if I right-click on a *subfolder* or file, I see the "Remote Sync" menu of options (and can sync that individual subfolder or file). I just cannot seem to sync the entire project via the top-level project folder

I've also tried completely uninstalling and reinstalling RemoteSync v4.1.6, but the behavior is unchanged after reinstallation.

**Comment by mputilin** [comment]
Having the same on Atom 1.21.1 x64 (MacOS High Sierra)

**Comment by manegame** [comment]
Same on Atom 1.21.1 x64 MacOS Sierra

**Comment by daverickdunn** [comment]
Hi all, this was indeed an error. It's been patched once more... https://github.com/yongkangchen/remote-sync/commit/ee1f6376417e4f4edd17b8a14b95bda6d78559ae

**Comment by mputilin** [comment]
Confirming: Fixed in v4.1.7
