### ISSUE TITLE
🐛 Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.Rebuild Packages Package Settings

### ISSUE THREAD

**Issue by noudadrichem** [yongkangchen/remote-sync#449]
I'm a big fan of this package, but since the last update this bug keeps returning.. 🐛
I hope you can fix it, info is in the img 🔽🔽
![image](https://user-images.githubusercontent.com/16288476/31765135-aef3d602-b4c3-11e7-8051-78a38004f765.png)

**Comment by daverickdunn** [comment]
Did you try rebuild the package? Uninstall re-install?

**Comment by noudadrichem** [comment]
@daverickdunn I did, as it says. It's just keeps saying after every reload or restart. That's why I made an issue out of it.

**Comment by daverickdunn** [comment]
Which version of Atom are you running?

**Comment by noudadrichem** [comment]
@daverickdunn 1.20.0 x64 MacOS 10.12.6 (Sierra)

**Comment by daverickdunn** [comment]
1.21.1 or 1.22.0-beta1 are the latest versions of Atom, please try either as the last patch was tested for both of those. Since Atom changed some CSS class names it may not work correctly for older versions.

**Comment by keisuke-nakata** [comment]
uninstall & install work fine for me.
