### ISSUE TITLE
ignore patterns do not seem to work

### ISSUE THREAD

**Issue by rbaprado** [yongkangchen/remote-sync#45]
Hello,

Disclaimer: I am not that familiar with minimatch and can be totally wrong ;-)

My ignore patterns do not seem to work:
  "target": "/home4/rbaprado",
  "ignore": [
    ".git/**",
    ".remote-sync.json",
    ".bash_history",
    ".bash_logout",
    ".bash_profile",
    ".bashrc",
    ".contactemail",
    ".cpanel",
    ".dns",
    ".emacs",
    ".ftpquota",
    ".gemrc",
    ".gitignore",
    ".htpasswds",
    ".kshrc",
    ".lastlogin",
    ".my.cnf",
    ".pki",
    ".trash",
    "access_logs",
    "etc",
    "mail/**",
    "moodlebetadata",
    "perl5",
    "tmp",
    "www"
  ]

When clicking on "Download All", files from, i.e., "mail/" are being downloaded. Am I doing something wrong?

Thanks in advance,
Renato

**Comment by SaifurRahmanMohsin** [comment]
It's better to ignore .remote-sync.json by default globally

**Comment by cristiantincu** [comment]
FWIW: I learned from [here](https://www.npmjs.com/package/glob#dots) that adding `node_modules/**/.*` alongside `node_modules/**` would achieve what I believe we all want. It works for me, at least. :grinning:
+@rbaprado +@finnishprince

**Comment by cristiantincu** [comment]
Behold my array of ignores!
```
"ignore": [
    ".git/**",
    ".remote-sync.json",
    "node_modules/**",
    "node_modules/**/.*"
  ]
```

**Comment by Jany-M** [comment]
This still doesnt work for FTP, on Win10, latest remote-sync as of today.
Folder that I've correctly set to ignore are still downloaded @yongkangchen
