### ISSUE TITLE
cannot get anything to work

### ISSUE THREAD

**Issue by marcucio** [yongkangchen/remote-sync#459]
I just did a clean install. I right clicked on project -> remote sync -> configure, nothing happens.

I also tried manually create the config file and still noting.

Is this supposed to work on OSX?

Thanks

**Comment by daverickdunn** [comment]
Yes it should work fine. Are there any error messages? Which version of atom are you running?

If there are JSON errors in **.remote-sync.json**, it will not load the package, however it currently leaves the menu options in the the context menu, they just do nothing, like you're describing. If this were the case however, it would have displayed a large error message within Atom at launch.

You could try putting nothing but `{ }` in **.remote-sync.json**, relaunching atom, then try open the configure menu. That should be more or less fool proof...

**Comment by marcucio** [comment]
I get the following error:

Failed to require the main module of 'remote-sync' because it requires one or more incompatible native modules (fsevents, binding, binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve.

I ran apm rebuild in /Users/mike/.atom/packages/remote-sync and I still get the same issue

**Comment by daverickdunn** [comment]
Which versions of Atom / Remote Sync are you using?

**Comment by marcucio** [comment]
I tried in atom 1.22.0
And atom beta 1.22.0 x64
the package.json for remote sync shows remote-sync@4.1.8

I also updated OSX recently to latest version
Maybe I need to rebuild all atom plugins? If so how would I do that?

**Comment by marcucio** [comment]
remote-sync 4.1.8

fsevents@1.1.3 – Cannot find module '/Users/mike/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v1.6-darwin-x64/fse.node'
binding@1.1.3 – Cannot find module '/Users/mike/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.3 – Cannot find module '/Users/mike/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.3 – Cannot find module '/Users/mike/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.3 – Cannot find module '/Users/mike/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.3 – Cannot find module '/Users/mike/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'
binding@1.1.3 – Cannot find module '/Users/mike/.atom/packages/remote-sync/node_modules/fsevents/lib/binding'

**Comment by daverickdunn** [comment]
> Maybe I need to rebuild all atom plugins? If so how would I do that?

Just what I was about to mention...

apm can get into a bit of a tizzy, it seems, if it has been upgrading packages for a while. You can try deleting: `/Users/mike/.atom/packages/remote-sync/node_modules` and running `apm rebuild` again (Sometimes it's the cached downloads that are corrupted, or incorrect versioned, etc.)

This post about another package might have some useful info: https://github.com/icetee/remote-ftp/issues/839

**Comment by marcucio** [comment]
apm rebuild from within atom seemed to fix, from the command line it did not fix

thanks for the help

**Comment by daverickdunn** [comment]
Good stuff!
