### ISSUE TITLE
Ignoring all folders with a specific name (for sync), rather than having to enter all paths?

### ISSUE THREAD

**Issue by ghost** [yongkangchen/remote-sync#461]
I would like to ignore any and all folders in any project called "node_modules".

I was hoping it would be OK to do something like `node_modules/**` or `.node_modules/**` or even `*node_modules/**` or `*/node_modules/**` or possibly `**/node_modules/**`. Looks like each project folder has to be specifically added from the main project root folder, like this:

```
testflowtest/TestFlow/src/node_modules/**, myExpressTestTest/lambda/custom/node_modules/**, mozdemo/node_modules/**, alexa-skill-sample-nodejs-express/node_modules/**
```

I would love to know an easier way, if possible!

**Comment by daverickdunn** [comment]
```
  "ignore": [
    ".remote-sync.json",
    ".git/**",
    "**/test_dir/**"
  ]
```

Is working fine for me. 

Note that in the example below, _test2.txt_ is uploaded, but _test_dir_ is ignored.

![image](https://user-images.githubusercontent.com/7645242/33373953-085ec1ea-d4fc-11e7-818f-b952cc0cf94c.png)


Can you give any more information about your OS, Atom, and Remote-Sync versions?

**Comment by ghost** [comment]
Arrrgh! Thank you for the quick reply, and with many apologies - it was only when I thought of opening the config file that I realised I had missed a comma on the config line, which of course stopped **/thing/** working, which was why I thought it didn't work.

` **/node_modules/**` does indeed work. Thank you!

**Comment by daverickdunn** [comment]
No worries, I added some JSON validation at launch recently, but should probably do the same for when the package reloads, thus avoiding that all too easy mistake...
