### ISSUE TITLE
Settting local source path

### ISSUE THREAD

**Issue by chodorowicz** [yongkangchen/remote-sync#51]
I would like to upload files only from a subfolder of my project (`./dev/` lets say). Is it possible? If not could this be added?

**Comment by pisandelli** [comment]
That will be great.
+1

**Comment by leobasilio** [comment]
I don't get it. You could right click the folder and select "Upload Folder". Isn't it what you mean?

**Comment by pisandelli** [comment]
Upload Folder works fine.
I want to define what folder I want to upload using autosave.

I have a project folder with several other folders.
- Project  
-- prototypes  
-- wordpress  
-- -- my_theme

I just want to upload **'my_theme'** to the server using `autosave`.

Right click on **'wordpress'** and configure remotesync on it doesn't work. The root folder will always be **'Project'**.  
I can ignore the other folders pretty well. But I want to upload just **'my_theme'** not **'wordpress/my_theme'**.  
Using `ignore` parameter like **"target": "/my_website/wp-content/themes/"**, it uploads to `local_server/my_website/wp-content/themes/wordpress/my_theme`. It should be `local_server/my_website/wp-content/themes/my_theme`.  
I'm not saying it's a bug. The behavior is perfect. But I need a way to specify the root folder as **'wordpress/'**.  
My workaround for now is to rename **'wordpress'** to **'themes'** and use the `ignore`parameter like **"target": "/my_website/wp-content/"**, but I don't like to adapt my workflow to a tool...

Cheers! :)

**Comment by chodorowicz** [comment]
@pisandelli yep, that was exactly what I meant. I would be nice to define both source (project relative) and target. E.g. like here: https://github.com/evanplaice/node-ftpsync

**Comment by leobasilio** [comment]
I see. I just pushed a new branch to my fork with this new feature. Would you please check it out before I open a pull request?

https://github.com/leobasilio/remote-sync/tree/sourceroot

I've added a "source" setting, which will basically be appended to the project root path, making the package work with this subdir as if it were the real root.

**Comment by pisandelli** [comment]
Hi @leobasilio thanks!
I just downloaded your package, uninstall remotesync, installed your package.. but couldn't find the 'source' option.
Maybe I'm missing something?

**Comment by leobasilio** [comment]
You should set it in your config file (.remote-sync.json).

**Comment by leobasilio** [comment]
Hi. Did it work as expected?

**Comment by pisandelli** [comment]
Sorry by the late... It works like a charm
Juste added `  "source": "/my_root_folder"`

Thanks

**Comment by chodorowicz** [comment]
nice :+1:
