### ISSUE TITLE
Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by RJHsiao** [yongkangchen/remote-sync#53]
Hi all,

I tried to upload/download a file/folder to/from a remote sftp server with Remote Sync 2.1.3, Atom 0.144.0 and Windows 8.1 x64.
But it always show me "Error: Timed out while waiting for handshake", and nothing is upload/download.
This is my `.remote-sync.json` below:

```
{
    "transport": "scp",
    "hostname": "127.0.0.1",
    "port": 22,
    "username": "toor",
    "pasword": "toortoor",
    "target": "/real/path/in/my/server",
    "ignore":[
        ".git/**"
    ]
}
```
BTW, please don't try to hack my server if you don't know that is a joke :stuck_out_tongue_winking_eye:

**Comment by jonathanbell** [comment]
Same issue on Ubuntu 12.04 w/ a SFTP server.

**Comment by jaywhy13** [comment]
This worked for me when I changed the transport to sftp.

**Comment by RobertWarrenGilmore** [comment]
I have tried:
* changing transport type from scp to sftp.
* changing readyTimeout to 99999.
* all three authentication strategies (useAgent, password, and privateKey)

I am still getting this error.

**Comment by teh1** [comment]
I strongly advise that you expose this "readyTimeout" parameter in the remote-sync.json configuration file. If a server takes longer than 5 seconds to connect (which can happen under load), the upload will time out. Changing this to 60 seconds fixed my issue. I would prefer to be able to specify this in my config file.

**Comment by mgcrea** [comment]
:+1: Encountering this while working on high latency servers (eg. mainland china)

**Comment by adammhaile** [comment]
I recently noticed this same problem when I switched my development team over to using Atom. We work on all our code locally and use this extension to automatically push it to our dev servers. It worked for three of us, but failed for one with this same error. We tried all of the above suggestions to no avail. After multiple uninstall/reinstall cycles of both the extension and Atom itself, I opened up the remote-sync config UI and noticed something odd... Even though I set it up with password auth, it showed it was set for useAgent, even though that option was not set in the .remote-sync.json file, which *did* show a set password. So, we set the password again and save. After that, it worked. Sadly, I don't have the contents of the config from when it didn't work, so I'm not sure what changed. But it was generated using the UI in the first place, so maybe there's a bug that is creating a corrupt config?

Anyways, just wanted to throw that out there. It may not actually be a timeout at all. To further confirm that, we were able to connect to the same server via ssh and WinSCP without problem or delay.

**Comment by collinstocks** [comment]
I encountered this same problem, and setting the timeout to 30 seconds fixed the issue. I feel like 30 seconds should be the default, anyway. Five seconds is a ridiculously short time.

**Comment by omouse** [comment]
@collinstocks how and where in the code did you change the timeout?

The timeout setting should be available to users in the manage package view for remote-sync for realz.

**Comment by collinstocks** [comment]
@omouse See https://github.com/yongkangchen/remote-sync/issues/53#issuecomment-62511019

**Comment by refrain4121** [comment]
Encounter same issue last week and change timeout  setting is not working either. After days of search I found that I mess up my $path environment. When reset path variable to system default  everything works.  Hope this help someone.

**Comment by jokr** [comment]
https://github.com/yongkangchen/remote-sync/pull/197

**Comment by mattsawyer77** [comment]
I just installed this package and have the error mentioned here. I've tried setting the timeout high (shouldn't be necessary, as I'm on a low-latency network). I've restarted Atom several times, and /usr/bin/scp is on the path as indicated by process.env.PATH. Any suggestions?

**Comment by Adryan91** [comment]
Thanks @rajendrant. Your solution solved my issue.

**Comment by obfusticatedcode** [comment]
Thanks @rajendrant , this fixed me for me too.

**Comment by LucaColombi** [comment]
same problem, updating timeout still not work

**Comment by lidiamartinez** [comment]
Basic ftp settings, passive:true, correct password and host. Not working. Same problem here. I'm going to use filezilla 👎

**Comment by willenjs** [comment]
I achieved a different outcome adding the following:
"secure" : true
