### ISSUE TITLE
Diff/Download folder is broken

### ISSUE THREAD

**Issue by wyqydsyq** [yongkangchen/remote-sync#60]
When trying to download via either Download Folder or Diff Folder, I get the following error:

	TypeError: Cannot read property 'forEach' of undefined
	  at /home/damon/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:86:15
	  at /home/damon/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/get-uri/node_modules/ftp/lib/connection.js:439:14
	  at /home/damon/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/get-uri/node_modules/ftp/lib/connection.js:891:7
	  at Socket.<anonymous> (/home/damon/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/get-uri/node_modules/ftp/lib/connection.js:922:5)
	  at Socket.g (events.js:199:16)
	  at Socket.emit (events.js:104:17)
	  at Object.afterConnect [as oncomplete] (net.js:973:10)

Uploading/downloading files directly works fine.

A wild stab in the dark is that the forEach that's throwing the error is expecting a collection of remote files but is getting undefined - possible the extension isn't receiving a remote equivalent of `ls` correctly.

**Comment by yongkangchen** [comment]
@wyqydsyq is this issue still? After google: `Error: unable to make data connection`, I guess it has something to do with passive mode?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the still issue still exists please reply and we will look into it.
