### ISSUE TITLE
Diff tool detection is broken

### ISSUE THREAD

**Issue by wyqydsyq** [yongkangchen/remote-sync#61]
I'm running OpenSUSE 13.2, I have Meld 3.12 installed which is what I want to use as my diff tool.

When I try to run a diff using this extension I get the error: 

```
Check [difftool Command] in your settings (remote-sync). Command error: Error: Command failed: /bin/sh -c diffToolPath /home/damon/Projects/test/.remote-sync.json /tmp/remote-sync/.remote-sync.json /bin/sh: diffToolPath: command not found command: diffToolPath /home/damon/Projects/test/.remote-sync.json /tmp/remote-sync/.remote-sync.json
```

I have tried specifying all these options:

```
"difftoolPath": "meld",
"diffToolPath": "meld",
"difftoolCommand": "meld"
```

in `.remote-sync.json`, and refreshed the FTP (as well as restarted Atom completely) and it still doesn't seem to help. I've tried creating the following alias in my `.bashrc` and `.zshrc` (zsh is my default shell) and it still hasn't helped this plugin work:

```
alias diffToolPath="meld"
```

However, after creating this alias I can run this manually in my own shell:

```
diffToolPath /home/damon/Projects/test/.remote-sync.json /tmp/remote-sync/.remote-sync.json
```

And Meld will open the two files as expected.

**Comment by sykot** [comment]
sorry, can you please tell how and where will i set the difftoolPath?
