### ISSUE TITLE
Add watch functionallity

### ISSUE THREAD

**Issue by screendriver** [yongkangchen/remote-sync#65]
remote-sync works fine when I edit and save a file. But it does not upload any newly pasted files like images. If you copy a binary file, like an image, and paste it into a directory nothing happens.

**Comment by LukaszKrawczyk** [comment]
:+1:

**Comment by enoversum** [comment]
Any plans on implementing this? This is actually one of the few things I miss about your extension and Atom in general :wink: .

**Comment by robsonsobral** [comment]
@enoversum , the pull request #224 is waiting for conflicts to be fixed.

**Comment by enoversum** [comment]
Hi @robsonsobral , thanks for letting me know. So it’s up to @theproducer to fix it, which hasn’t happened since December I see :cry: .

**Comment by theproducer** [comment]
Hello!  Been in a cave working on some projects.

I've since switched to VSCode, but I'll get these conflicts fixed this week.

**Comment by enoversum** [comment]
@theproducer Wow, thanks for doing this and letting us know. Highly appreciated :heart: !

**Comment by enoversum** [comment]
@theproducer Hey there, the week has already passed, any updates on this matter? All the best ;).

**Comment by elistone** [comment]
This feature has now been implemented see #261 for more details.
