### ISSUE TITLE
Not all of folder is downloading?

### ISSUE THREAD

**Issue by zocheyado** [yongkangchen/remote-sync#73]
So I create the .remote-sync.json file, fill it all out, and the download begins (it downloads 3 out of the 7 folders in my remote DIR) but then It just stops, no errors, no progress bar no nothing. Does anyone know what is going on?
{
  "transport": "scp",
  "hostname": "example.com",
  "port": "22",
  "username": "****",
  "password": "*******",
  "target": "/srv/www/laravel",
  "ignore": [
    ".git/**"
  ],
  "uploadOnSave": true
}

**Comment by DSdavidDS** [comment]
I am having the same problem right now. Trying to sync a node project. only my node_modules folder and app.js is syncing
