### ISSUE TITLE
Difftool error message, Windows7, KDiff3

### ISSUE THREAD

**Issue by ownmaster** [yongkangchen/remote-sync#74]
Hi again.

I've set diff tool path to  `"c:\Program Files (x86)\KDiff3\kdiff3.exe"`, it works, but every time I launch diff there is an error message from remote-sync:
`Check [difftool Command] in your settings (remote-sync). Command error: Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""c:\Program Files (x86)\KDiff3\kdiff3.exe" <path_to_source_folder>\composer.json <path_to_temp_folder>\remote-sync\composer.json" command: "c:\Program Files (x86)\KDiff3\kdiff3.exe" <path_to_source_folder>\composer.json <path_to_temp_folder>\remote-sync\composer.json`

**Comment by dmnBrest** [comment]
The same error

**Comment by yongkangchen** [comment]
Already fixed in latest version, please update and try again. Thanks
