### ISSUE TITLE
Sync to mounted folder?

### ISSUE THREAD

**Issue by ColCh** [yongkangchen/remote-sync#80]
Hi! I have mounted my NFS remote folder to some path. How can I specify this path and sync to it using this plugin? 

For example, in Sublime text we have [bcharbonnier/SublimeFileSync](https://github.com/bcharbonnier/SublimeFileSync)

Yep may be it's feature request - sync to __local__ dir, not to scp\ftp\sftp

**Comment by yongkangchen** [comment]
Duplicate with #179
