### ISSUE TITLE
Authentication failure with all methods on SFTP

### ISSUE THREAD

**Issue by MiquelAdell** [yongkangchen/remote-sync#81]
Hi,

I have trouble using SFTP with remote-sync on **some** servers.

I use it without problem with all my FTP connections but some SFTP connections never get to work.
I'm comparing both hosts and I don't find any difference.

I can connect to the faulty host using filezilla. But I can not connect via ssh in a terminal because the server only accepts SFTP connections.

The problem is the following:
I set up sync via clicking on it's name on the bottom bar.
Open all filelds and choose "password"
I get the following:

    Error: Authentication failure. Available authentication methods: publickey,keyboard-interactive

If i choose user agent and save again I get:

    Error: Authentication failure. Available authentication methods: undefined

I'm not an expert with SSH but I think that if I can not log via terminal to the server with SSH I will not be able to test the private key method.

I know that this issue must be very difficult to reproduce because it seems particular to some servers... Is there any log I can check to see something more about this "undefined" I get when I use the user agent method?

Thanks!

**Comment by Trudko** [comment]
I have some problem for quite some time. I get error 
Error: Authentication failure. Available authentication methods: publickey,keyboard-interactive
My config looks something like this:
{
  "transport": "scp",
  "hostname": "ip address of server",
  "port": "22",
  "username": "peter",
  "password": "my_password_value",
  "target": "/path/to/folder",
  "ignore": [
    ".git/**"
  ],
  "uploadOnSave": true
}

Environment is Windows 8.1. I have no problem with connecting using different IDE like netbeans or sublime text.

**Comment by Trudko** [comment]
@hanoc hi, have you find any workaround?

**Comment by hanoc** [comment]
No @trudko, I haven't and in fact I've gotten more errors on other servers.
The defining  factor of the bug seems to be the server.

For some servers I can't never get it to work all other variables being equal (configuration wise)  to other servers that do work. 

I've tried other plug-ins but I can't find any other that works as well as remote sync (when it works)
