### ISSUE TITLE
Upload not working, download working

### ISSUE THREAD

**Issue by nikolaydyankov** [yongkangchen/remote-sync#86]
I have followed these steps:

- create an empty folder with a .remote-sync.json file, "uploadOnSave" is "true"
- "remote sync reload config"
- "remote sync download all"

At this point it downloads all the files from my project, but whenever I make a change to a file, it doesn't upload. Not even when I right click a file and "Upload File".

Is there a workflow step that I'm missing?

P.S. The folder that I created is in my git repo.

**Comment by harmishhk** [comment]
i had same problem, however after restarting atom manual and auto upload works fine

**Comment by Pithikos** [comment]
Saved me hours of trying to get this working! Should probably mention it in the README
