### ISSUE TITLE
Unable to make data connection

### ISSUE THREAD

**Issue by Protossoario** [yongkangchen/remote-sync#91]
I am getting this error on a fresh install, when running Download All Files or Download Folder.

>Error: Unable to make data connection( Error: read ECONNRESET)
>Error: Unexpected data connection error: Error: read ECONNRESET

This is my config file:

```
{
  "transport": "ftp",
  "uploadOnSave": false,
  "hostname": "miadvenio.net",
  "port": "21",
  "target": "/public_html",
  "ignore": [
    ".git/**"
  ],
  "username": "miadvnet",
  "password": "*********"
}
```

**Comment by yongkangchen** [comment]
Duplicate with #204
