### ISSUE TITLE
Look for .remote-sync within the current Root Folder

### ISSUE THREAD

**Issue by nikolaydyankov** [yongkangchen/remote-sync#95]
In Atom v0.182.0 you can now add multiple Root Folders. I believe Remote Sync should look for the .remote-sync file within the Root Folder of the file that you are trying to upload, instead of the root of the project.

**Comment by brandensilva** [comment]
I agree completely. Currently being annoyed that it keeps searching in my .atom directory on Windows.

**Comment by yongkangchen** [comment]
Already support for multiple Root Folders
