### ISSUE TITLE
.remote-sync file should be in ignore list by default

### ISSUE THREAD

**Issue by hax** [yongkangchen/remote-sync#96]
Commonly there is no need to upload .remote-sync file.

**Comment by roelofr** [comment]
I disagree with this, since I use version control to sync changes between multiple PCs and use remote-sync to upload code to my deployment server.

So I guess this should be optional.

**Comment by egyptianbman** [comment]
I usually add this file to the ignore path.

**Comment by hax** [comment]
Note .remote-sync will contains credential info such as user/pwd, so auto upload it seems increase the security risk.

**Comment by raden** [comment]
so how to ignore the upload? i can't seem to find any option to disable this. it's very dangerous as it contains the key passphrase and password. i don't want to upload this file.

**Comment by hax** [comment]
@raden Currently you need to add it to ignore list manually. Here is a example:

```json
{
  "transport": "ftp",
  "hostname": "192.168.2.123",
  "port": 21,
  "username": "hax",
  "password": "就不告诉你密码",
  "target": "~/myproject",
  "ignore": [
    ".remote-sync.json",
    ".git/**",
    ".idea/**",
    "node_modules",
    "npm-debug.log"
  ]
}
```
