### ISSUE TITLE
Blanc input fields in Remote Configuration

### ISSUE THREAD

**Issue by jepediacreative** [yongkangchen/remote-sync#97]
When i open the config pop up all input fields stay blanc when entering text.
It creates the .json file correct on save and up / downloading is working fine.
Using remote-sync 2.4.0 / atom 0.184 (latest).

**Comment by edthepenguin** [comment]
Hi,

I've also experienced this. I know that the text I am inputting is valid as after saving, the json updates.
I've tried changing to a light theme to check that it's not theme-related but it still persists.

**Comment by jepediacreative** [comment]
i´ve also tried chaning the themes with no effect.
When i change the content manually in the json file and save it, it also wont update the setting.

**Comment by reggi** [comment]
I'm having the same problem.

**Comment by denyo256** [comment]
Same problem for me with all themes - light and dark

**Comment by mdotasia** [comment]
Same here.

**Comment by patrickgilmour** [comment]
+1

**Comment by visualcookie** [comment]
same. and i got this issue for 3 months now. anyone knows another package that actually works? i need the ignore function and to say that i want to upload on safe or not.

tried Remote-Sync, but it doesn't has this functionality atm.

**Comment by pyrokinetiq** [comment]
:+1:

**Comment by jepediacreative** [comment]
Workaround:
- just fill in your information and check in the created remote.sync.json
- rewrite the generated json file if needed
- hit cmd shift p (mac)
- enter Remote Sync: Reload Config

it is also strange that you cant just rewrite the json file and simply save the changes (which worked before) - now you have to update it with the command shown above.
